package com.vayunmathur.weather.ui.components

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import com.vayunmathur.library.ui.MaterialTheme
import com.vayunmathur.library.ui.IconCalendar
import com.vayunmathur.library.ui.Surface
import com.vayunmathur.library.ui.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.vayunmathur.weather.R
import com.vayunmathur.weather.network.ForecastResponse
import com.vayunmathur.weather.util.TemperatureUnit
import com.vayunmathur.weather.util.computeDaySummary

/**
 * Port of WeatherMaster's `SummaryCard`. `Surface(shape = extraLarge,
 * color = surface, shadowElevation = 2.dp)` containing a [CardsHeader] and
 * a body Text generated by [computeDaySummary].
 */
@Composable
fun SummaryCard(forecast: ForecastResponse, tempUnit: TemperatureUnit) {
    val summary = computeDaySummary(forecast, tempUnit)
    Surface(
        color = MaterialTheme.colorScheme.surface,
        shape = MaterialTheme.shapes.extraLarge,
        shadowElevation = 2.dp,
    ) {
        Column(modifier = Modifier.fillMaxWidth().padding(bottom = 16.dp)) {
            CardsHeader(text = "Summary", icon = { m, c -> IconCalendar(m, c) })
            Spacer(Modifier.height(8.dp))
            Text(
                text = summary,
                modifier = Modifier.padding(horizontal = 16.dp),
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface,
            )
        }
    }
}
